# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y34KKm-GTy4MLNvDE_QYpLTAUlWq7A_P
"""

import ee

ee.Authenticate()
ee.Initialize(project="ee-yulinjiang68")

def prepare_l4l5l7_col2(image):
    band_list = ['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B7']
    sub_band = ['BLUE', 'GREEN', 'RED', 'NIR', 'SWIR1', 'SWIR2']

    optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)
    scaled = optical_bands.select(band_list).rename(sub_band)

    valid_qa = [5440, 5504]

    mask1 = image.select(['QA_PIXEL']).remap(valid_qa, [1] * len(valid_qa), 0)
    mask2 = image.select('QA_RADSAT').eq(0)
    mask3 = scaled.select(sub_band).reduce(ee.Reducer.min()).gt(0)
    mask4 = scaled.select(sub_band).reduce(ee.Reducer.max()).lt(1)
    mask5 = image.select("SR_ATMOS_OPACITY").unmask(-1).lt(300)

    return scaled.updateMask(mask1.And(mask2).And(mask3).And(mask4).And(mask5)).multiply(1e4).copyProperties(image, ['system:time_start'])

def prepare_l8_col2(image):
    band_list = ['SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7']
    sub_band = ['BLUE', 'GREEN', 'RED', 'NIR', 'SWIR1', 'SWIR2']

    optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)
    scaled = optical_bands.select(band_list).rename(sub_band)

    valid_toa = [2, 4, 32, 66, 68, 96, 100, 130, 132, 160, 164]
    valid_qa = [21824, 21888]

    mask1 = image.select(['QA_PIXEL']).remap(valid_qa, [1] * len(valid_qa), 0)
    mask2 = image.select('QA_RADSAT').eq(0)
    mask3 = scaled.select(sub_band).reduce(ee.Reducer.min()).gt(0)
    mask4 = scaled.select(sub_band).reduce(ee.Reducer.max()).lt(1)
    mask5 = image.select(['SR_QA_AEROSOL']).remap(valid_toa, [1] * len(valid_toa), 0)

    return scaled.updateMask(mask1.And(mask2).And(mask3).And(mask4).And(mask5)).multiply(1e4).copyProperties(image, ['system:time_start'])

def getLandsat(start, end, endl7, roi):
    collection8 = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2').filterDate(start, end).map(prepare_l8_col2);
    collection7 = ee.ImageCollection('LANDSAT/LE07/C02/T1_L2').filterDate(start, endl7).map(prepare_l4l5l7_col2);
    collection5 = ee.ImageCollection('LANDSAT/LT05/C02/T1_L2').filterDate(start, end).map(prepare_l4l5l7_col2);
    collection4 = ee.ImageCollection('LANDSAT/LT04/C02/T1_L2').filterDate(start, end).map(prepare_l4l5l7_col2);
    col = collection4.merge(collection5).merge(collection7).merge(collection8).filterBounds(roi)
    return col

table = ee.FeatureCollection("projects/ee-yulinjiang68/assets/Himalaya_grid") # Use ArcMap to generate a study-area grid in WGS84 coordinates
tSize = table.size().getInfo()
tList = table.toList(tSize)

geo_dict = {}
for i in range(tSize):
    feature = ee.Feature(tList.get(i))
    # FID = feature.get('FID_').getInfo()
    geo = feature.geometry().getInfo()
    geo_dict[i] = geo['coordinates']

def buildCoefsRMSEMagnitude(fit, nSegments, targetBand):
  # Build coefficient, RMSE, and magnitude images from the CCDC result
    segmentTag = [f"S{i}" for i in range(1, nSegments + 1)]
    zeros = ee.Image(ee.Array(ee.List.repeat(0, nSegments)))

    # Build the magnitude image
    magImg = fit.select(targetBand + '_magnitude').arrayCat(zeros, 0).float().arraySlice(0, 0, nSegments)
    magImages = magImg.arrayFlatten([ee.List([tag + '_' + targetBand + '_MAG' for tag in segmentTag])])
    zeros = ee.Image(ee.Array(ee.List.repeat(0, nSegments)))
    # Build the RMSE image
    rmseImg = fit.select(targetBand + '_rmse').arrayCat(zeros, 0).float().arraySlice(0, 0, nSegments)
    rmseImages = rmseImg.arrayFlatten([ee.List([tag + '_' + targetBand + '_RMSE' for tag in segmentTag])])
    # Build the coefficient image
    bandTag = targetBand + '_coefs'
    harmonicTag = ['INTP','SLP','COS','SIN','COS2','SIN2','COS3','SIN3']
    zeros = ee.Image(ee.Array([ee.List.repeat(0, len(harmonicTag))])).arrayRepeat(0, nSegments)
    coefImg = fit.select(bandTag).arrayCat(zeros, 0).float().arraySlice(0, 0, nSegments)
    tags = [tag + '_' + targetBand + '_coef' for tag in segmentTag]
    coefImages = coefImg.arrayFlatten([tags, harmonicTag])
    return ee.Image.cat(coefImages, magImages, rmseImages)

def buildStartEndBreakProb(fit, nSegments, tag):
  # Build breakpoint information images from the CCDC result (tStart, tEnd, tBreak, changeProb)
    segmentTag = [f"S{i}_{tag}" for i in range(1, nSegments + 1)]
    zeros = ee.Array(0).repeat(0, nSegments)
    magImg = fit.select(tag).arrayCat(zeros, 0).float().arraySlice(0, 0, nSegments)
    return magImg.arrayFlatten([segmentTag])

def buildCcdImage(fit, nSegments):
    # tProb_filtered = tProb.updateMask(tProb.eq(1)) can be used to export only pixels with prob = 1
    tProb = buildStartEndBreakProb(fit, nSegments, 'changeProb')
    tStart = buildStartEndBreakProb(fit, nSegments, 'tStart')
    tEnd = buildStartEndBreakProb(fit, nSegments, 'tEnd')
    tBreak = buildStartEndBreakProb(fit, nSegments, 'tBreak')
    return ee.Image.cat(tStart, tEnd, tBreak, tProb);

bandList = ['BLUE','GREEN','RED','NIR','SWIR1','SWIR2'] # Target bands used to compute coefficients

for key, value  in geo_dict.items():
    roi = ee.Geometry.Polygon(value)
    landsat_col = getLandsat('1995-01-01', '2025-04-01', '2021-10-01', roi)
    # print(landsat_col.first().getInfo())
    ccd_result = ee.Algorithms.TemporalSegmentation.Ccdc(
        collection=landsat_col,
        breakpointBands=['BLUE','GREEN','RED','NIR','SWIR1','SWIR2'],
        tmaskBands=['GREEN','SWIR1'],
        dateFormat=1,
        chiSquareProbability=0.99
    )

    # The following exports breakpoint timing information; tStart, tBreak, and tEnd are in year + fractional-year format, where the fractional part multiplied by 365 or 366 gives DOY
    ccdImage = buildCcdImage(ccd_result, 6).clip(roi)

    # Create the Breaks export task
    task = ee.batch.Export.image.toDrive(
        image=ccdImage,
        description=f"{key}_breaks",
        folder="Himalaya_breaks",
        region=roi,
        scale=30,
        maxPixels=1e13,
        fileFormat='GeoTIFF'
    )

    print(task)
    task.start()


    # The following exports coefficients in two possible ways: exporting all bands together or exporting each band separately. Only one of these approaches should be enabled at a time.
    # 1. Export harmonic coefficients for all bands together
    coef_images = ee.Image([buildCoefsRMSEMagnitude(ccd_result, 6, tband) for tband in bandList]) # Generate coefficient images

    # Create the Coefficients export task
    coef_task = ee.batch.Export.image.toDrive(
        image=coef_images,
        description=f"{key}_coefs",
        folder="Himalaya_coefs",
        region=roi,
        scale=30,
        maxPixels=1e13,
        fileFormat='GeoTIFF'
    )

    print(coef_task)
    coef_task.start()


    # 2. Export harmonic coefficients by band
    # for tband in bandList:
    #     tbandCoef = buildCoefsRMSEMagnitude(ccd_result, 6, tband)
    #     coef_task = ee.batch.Export.image.toDrive(
    #         image=tbandCoef,
    #         description=f"{key}_{tband}",
    #         folder="ccd_coef_Image",
    #         region=roi,
    #         scale=30,
    #         maxPixels=1e13,
    #         fileFormat='GeoTIFF'
    #     )
    #     print(coef_task)
    #     coef_task.start()

